/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.app;

import cl.model.Cliente;
import cl.model.Conexion;
import cl.model.Data;
import cl.model.TipoVivienda;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author JOAQUIN CABELLO
 */
public class Vendedor extends javax.swing.JFrame {
    private ListaVivienda lv;
    private Data d;
    private App a;
    private Conexion c;
    private TipoVivienda t;
    private String orden;
    private List<TipoVivienda> tipoVivienda;

    public Vendedor() {
        initComponents();
        a = new App();
        tipoVivienda = new ArrayList<>();
        try {
            d = new Data();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Vendedor.class.getName()).log(Level.SEVERE, null, ex);
        }
        vivienda();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameCambiarApariencia = new javax.swing.JFrame();
        btgOrden = new javax.swing.ButtonGroup();
        jpjVentaArriendo = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtNombreCliente4 = new javax.swing.JTextField();
        txtRutCliente4 = new javax.swing.JTextField();
        txtSueldoCliente4 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        rbDescendente1 = new javax.swing.JRadioButton();
        rbAscendente1 = new javax.swing.JRadioButton();
        btnBuscarVivienda1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cboTipoVivienda1 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        txtVivenda = new javax.swing.JTextField();
        lblVivienda = new javax.swing.JLabel();
        btnRegistrarCliente4 = new javax.swing.JButton();
        btnCambiarBoton = new javax.swing.JButton();
        btnCambiarL = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNombreTrabajador = new javax.swing.JTextField();

        javax.swing.GroupLayout frameCambiarAparienciaLayout = new javax.swing.GroupLayout(frameCambiarApariencia.getContentPane());
        frameCambiarApariencia.getContentPane().setLayout(frameCambiarAparienciaLayout);
        frameCambiarAparienciaLayout.setHorizontalGroup(
            frameCambiarAparienciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        frameCambiarAparienciaLayout.setVerticalGroup(
            frameCambiarAparienciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpjVentaArriendo.setBorder(javax.swing.BorderFactory.createTitledBorder("Venta/Arriendo"));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        jLabel13.setText("Nombre: ");

        jLabel14.setText("Rut: ");

        jLabel15.setText("Sueldo: ");

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda"));

        btgOrden.add(rbDescendente1);
        rbDescendente1.setText("DESC");
        rbDescendente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDescendente1ActionPerformed(evt);
            }
        });

        btgOrden.add(rbAscendente1);
        rbAscendente1.setText("ASC");
        rbAscendente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAscendente1ActionPerformed(evt);
            }
        });

        btnBuscarVivienda1.setText("Buscar");
        btnBuscarVivienda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVivienda1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Orden: ");

        jLabel16.setText("Vivienda: ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(rbDescendente1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbAscendente1))
                    .addComponent(cboTipoVivienda1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscarVivienda1)
                .addGap(328, 328, 328))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbDescendente1)
                    .addComponent(rbAscendente1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTipoVivienda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarVivienda1)
                    .addComponent(jLabel16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblVivienda.setText("Vivienda: ");

        btnRegistrarCliente4.setText("Registrar");
        btnRegistrarCliente4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarCliente4ActionPerformed(evt);
            }
        });

        btnCambiarBoton.setText("Cambiar Color Boton");
        btnCambiarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarBotonActionPerformed(evt);
            }
        });

        btnCambiarL.setText("Cambiar Letra Boton");
        btnCambiarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblVivienda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVivenda, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addComponent(jLabel15)
                                            .addGap(23, 23, 23))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addGap(18, 18, 18)))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnRegistrarCliente4, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                    .addComponent(txtNombreCliente4)
                                    .addComponent(txtRutCliente4)
                                    .addComponent(txtSueldoCliente4)))
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCambiarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCambiarL, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtNombreCliente4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtRutCliente4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtSueldoCliente4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarCliente4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVivenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVivienda))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCambiarBoton)
                    .addComponent(btnCambiarL))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Nombre:");

        javax.swing.GroupLayout jpjVentaArriendoLayout = new javax.swing.GroupLayout(jpjVentaArriendo);
        jpjVentaArriendo.setLayout(jpjVentaArriendoLayout);
        jpjVentaArriendoLayout.setHorizontalGroup(
            jpjVentaArriendoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpjVentaArriendoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpjVentaArriendoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpjVentaArriendoLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpjVentaArriendoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jpjVentaArriendoLayout.setVerticalGroup(
            jpjVentaArriendoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpjVentaArriendoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpjVentaArriendoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpjVentaArriendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpjVentaArriendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarCliente4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarCliente4ActionPerformed

        try {
            String nombre = txtNombreCliente4.getText();
            String rut = txtRutCliente4.getText();
            int sueldo = Integer.parseInt(txtSueldoCliente4.getText());

            Cliente c = new Cliente(rut, nombre, sueldo);

            d.registrarCliente(c);

            txtNombreCliente4.setText(null);
            txtRutCliente4.setText(null);
            txtSueldoCliente4.setText(null);

            JOptionPane.showMessageDialog(this, "Cliente registrado!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }


    }//GEN-LAST:event_btnRegistrarCliente4ActionPerformed

    private void rbDescendente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDescendente1ActionPerformed
        orden = "Descendete";
    }//GEN-LAST:event_rbDescendente1ActionPerformed

    private void rbAscendente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAscendente1ActionPerformed
        orden = "Ascendente";
    }//GEN-LAST:event_rbAscendente1ActionPerformed

    private void btnBuscarVivienda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVivienda1ActionPerformed
        orden();
        t = (TipoVivienda) cboTipoVivienda1.getSelectedItem();

        try {
            d.buscarVivienda(t);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        lv = new ListaVivienda();
        lv.setVisible(true);
        dispose();

    }//GEN-LAST:event_btnBuscarVivienda1ActionPerformed

    private void btnCambiarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarBotonActionPerformed
        Color c = JColorChooser.showDialog(rootPane, "Elija un color", this.getBackground());

        btnBuscarVivienda1.setBackground(c);
        btnCambiarBoton.setBackground(c);
        btnRegistrarCliente4.setBackground(c);
        btnCambiarL.setBackground(c);


    }//GEN-LAST:event_btnCambiarBotonActionPerformed

    private void btnCambiarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarLActionPerformed
        Color c = JColorChooser.showDialog(rootPane, "Elija un color", this.getBackground());
        btnBuscarVivienda1.setForeground(c);
        btnCambiarBoton.setForeground(c);
        btnRegistrarCliente4.setForeground(c);
        btnCambiarL.setForeground(c);
    }//GEN-LAST:event_btnCambiarLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgOrden;
    private javax.swing.JButton btnBuscarVivienda1;
    private javax.swing.JButton btnCambiarBoton;
    private javax.swing.JButton btnCambiarL;
    private javax.swing.JButton btnRegistrarCliente4;
    private javax.swing.JComboBox<TipoVivienda> cboTipoVivienda1;
    private javax.swing.JFrame frameCambiarApariencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jpjVentaArriendo;
    private javax.swing.JLabel lblVivienda;
    private javax.swing.JRadioButton rbAscendente1;
    private javax.swing.JRadioButton rbDescendente1;
    private javax.swing.JTextField txtNombreCliente4;
    private javax.swing.JTextField txtNombreTrabajador;
    private javax.swing.JTextField txtRutCliente4;
    private javax.swing.JTextField txtSueldoCliente4;
    private javax.swing.JTextField txtVivenda;
    // End of variables declaration//GEN-END:variables

    
    public void vivienda() {
        tipoVivienda.add(new TipoVivienda(1, "Casa"));
        tipoVivienda.add(new TipoVivienda(2, "Departamento"));

        tipoVivienda.forEach((tipoVivienda1) -> {
            cboTipoVivienda1.addItem(tipoVivienda1);
        });
    }

    public void orden() {
        try {
            String tipo1 = rbAscendente1.getActionCommand();
            String tipo2 = rbDescendente1.getActionCommand();

            TipoVivienda v = new TipoVivienda(tipo1);
            TipoVivienda vi = new TipoVivienda(tipo2);

            if ("Descendete".equals(orden)) {
                d.orderByDesc(vi);
                JOptionPane.showMessageDialog(this, "Ordenado de forma Descendente Por el precio!");

            } else {
                d.orderByAsc(v);
                JOptionPane.showMessageDialog(this, "Ordenado de forma Ascendente Por el precio!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

}
